version: "1.1"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=12345678
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  bimp-test-app:
    build: .
    ports:
      - 8000:8000
    environment:
      - POSTGRES_PASSWORD=12345678
      - APP_PORT=8000
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
